# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5Bokete' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift5Bokete
pod 'SwiftyJSON'
pod 'Alamofire', '~> 5.00-beta.5'
pod 'SDWebImage'

end
