# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift6ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift6ChatApp
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  pod 'ViewAnimator'
  pod 'Firebase/Storage'
  pod 'SDWebImage', '~> 5.0'
end
