# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift6Tiktok' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift6Tiktok
  pod "SwiftyCam"
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftVideoGenerator'
  pod 'SDWebImage', '~> 5.0'
  pod 'NVActivityIndicatorView'
end
