# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5IntroApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift5IntroApp
pod 'lottie-ios'
pod 'SegementSlide', '3.0.1'
pod 'ImpressiveNotifications'
end
